# Generated by Django 6.0.7 on 2026-07-25 05:27

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def populate_on_hand(apps, schema_editor):
    Inventory = apps.get_model('parts', 'Inventory')
    for inv in Inventory.objects.all():
        inv.on_hand = (inv.available or 0) + (inv.reserved or 0) + (inv.damaged or 0)
        inv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_demanded', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecast_horizon', models.IntegerField(choices=[(7, '7 Days'), (30, '30 Days'), (90, '90 Days')], default=30)),
                ('predicted_demand', models.FloatField()),
                ('forecasting_method', models.CharField(default='WEIGHTED_MOVING_AVERAGE', max_length=50)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=20)),
                ('confidence_score', models.FloatField(default=0.85)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('RESERVATION', 'Reservation'), ('RELEASE', 'Release'), ('SHIPMENT', 'Shipment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage'), ('RETURN', 'Return')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('reference_type', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=100)),
                ('reference_line_id', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('CRITICAL_STOCKOUT', 'Critical Stockout'), ('LOW_INVENTORY', 'Low Inventory'), ('ORDER_DELAY', 'Order Delay'), ('TRANSFER_REQUIRED', 'Transfer Required'), ('SUPPLIER_DELAY', 'Supplier Delay')], max_length=50)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('active_condition_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_allocated', models.PositiveIntegerField(default=0)),
                ('quantity_fulfilled', models.PositiveIntegerField(default=0)),
                ('quantity_backordered', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('HOLD', 'Hold'), ('TRANSFER', 'Transfer'), ('REORDER', 'Reorder'), ('EXPEDITE', 'Expedite')], max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('confidence', models.CharField(default='HIGH', max_length=20)),
                ('priority', models.CharField(default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISPATCHED', 'Dispatched'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=30)),
                ('estimated_transit_days', models.IntegerField(default=5)),
                ('actual_transit_days', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='damaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='in_transit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='maximum_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='on_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='safety_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_fulfillment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled'), ('BACKORDERED', 'Backordered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='parts.warehouse'),
        ),
        migrations.AddField(
            model_name='part',
            name='maximum_stock',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='part',
            name='safety_stock',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier_lead_time_days',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier_name',
            field=models.CharField(default='ABC Components', max_length=200),
        ),
        migrations.AddField(
            model_name='part',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=2500.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='parts.dealer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.part'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='part',
            name='criticality',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=50),
        ),
        migrations.RunPython(populate_on_hand, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand__gte', django.db.models.expressions.CombinedExpression(models.F('reserved'), '+', models.F('damaged')))), name='check_on_hand_gte_reserved_damaged'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('damaged__gte', 0), ('in_transit__gte', 0), ('incoming__gte', 0), ('on_hand__gte', 0), ('reserved__gte', 0)), name='check_non_negative_inventory_counts'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandhistory',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_histories', to='parts.part'),
        ),
        migrations.AddField(
            model_name='demandhistory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_histories', to='parts.warehouse'),
        ),
        migrations.AddField(
            model_name='forecastresult',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part'),
        ),
        migrations.AddField(
            model_name='forecastresult',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='parts.inventory'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parts.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_as_source', to='parts.warehouse'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_as_target', to='parts.warehouse'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='parts.warehouse'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='parts.warehouse'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_recommendation', to='parts.stocktransfer'),
        ),
        migrations.AlterUniqueTogether(
            name='demandhistory',
            unique_together={('part', 'warehouse', 'date')},
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.UniqueConstraint(fields=('reference_type', 'reference_id', 'transaction_type', 'reference_line_id'), name='unique_transaction_event'),
        ),
    ]
